insert into cie9(cve,descripcion) values
('00.10','Implantación de agente quimioterapéutico'),
('00.11','Infusión de drotrecogin alfa (activada)'),
('00.12','Administración de óxido nítrico inhalado'),
('00.13','Inyección o infusión de nesiritide'),
('00.14','Inyección o infusión de antibióticos del grupo de la oxazolidinona'),
('00.15','Infusión de dosis alta de interleucina-2 [IL-2]'),
('00.16','Tratamiento presurizado de injerto de derivación venoso [conducto] con sustancia medicamentosa'),
('00.17','Infusión de agente vasopresor'),
('00.18','Terapia de infusión de anticuerpos inmunosupresores'),
('00.19','Irrupción de la barrera hematoencefálica vía infusión (IBH) [BBBD]'),
('00.50','Implantación de marcapasos de resincronización cardíaca sin mención de desfibrilación, sistema MRC] [CRT-P]'),
('00.53','Implantación o sustitución de marcapasos de resincronización cardiaca,sólo generador de pulso [IMRC] CRT-P]'),
('00.54','Implantación o sustitución de desfibrilador de resincronización cardiaca, sólo dispositivo generador de pulso [DRC] [CRT-D]'),
('00.80','Revisión de sustitución de rodilla, total (todos los componentes)'),
('00.81','Revisión de sustitución de rodilla, componente tibial'),
('00.82','Revisión de sustitución de rodilla, componente femoral'),
('00.83','Revisión de sustitución de rodilla, componente rotuliano'),
('00.84','Revisión de sustitución total de rodilla, inserción (alineador) tibial'),
('00.C5','Terapia ocupacional en lesiones de mano y extremidad superior'),
('00.C6','Terapia ocupacional en paciente pediátrico'),
('00.C7','Terapia ocupacional en paciente neurológico'),
('00.C8','Terapia ocupacional: adiestramiento en cuidado y uso de órtesis en pacientes amputados'),
('00.C9','Terapia ocupacional: adiestramiento en cuidado y uso de prótesis en pacientes amputados'),
('00.F3','Aplicación tópica de flúor'),
('00.F8','Control de placa dentobacteriana'),
('00.F9','Curación de herida'),
('00.G1','Drenaje de absceso dentario'),
('00.H8','Instalación de sonda vesical'),
('00.H9','Retiro de sonda vesical'),
('02.34','Derivación ventricular a la cavidad y órganos abdominales'),
('02.41','Irrigación y exploración de derivación ventricular'),
('02.42','Sustitución de derivación ventricular'),
('02.43','Extracción de derivación ventricular'),
('11.31','Transposición de pterigión'),
('11.32','Excisión de pterigión con injerto corneal'),
('11.39','Otra excisión de pterigión'),
('12.11','Iridotomía con transfixión'),
('12.12','Otra iridotomía'),
('12.13','Excisión de iris prolapsado'),
('12.14','Otra iridectomía'),
('13.2X','Extracción extracapsular de cristalino mediante técnica de extracción lineal'),
('13.3X','Extracción extracapsular de cristalino mediante técnica simple sencilla de aspiración (e irrigación)'),
('13.41','Facoemulsificación y aspiración de catarata'),
('13.42','Facofragmentación mecánica y aspiración de catarata por ruta posterior'),
('13.43','Facofragmentación mecánica y otra aspiración de catarata'),
('13.71','Inserción de prótesis de cristalino intraocular en el momento de la extracción de la catarata, una sola etapa'),
('15.11','Recesión de un músculo extraocular'),
('15.12','Avance de músculo extraocular'),
('15.13','Resección de un músculo extraocular'),
('15.19','Otras operaciones sobre un músculo extraocular con desprendimiento temporar del globo ocular'),
('15.21','Procedimiento de alargamiento sobre un músculo extraocular'),
('15.22','Procedimiento de acortamiento sobre un músculo extraocular'),
('15.29','Otra operación sobre un músculo extraocular'),
('15.3X','Operaciones sobre dos o más músculos extraoculares con desprendimiento temporal del globo ocular, uno o ambos ojos'),
('15.4X','Otras operaciones sobre dos o más músculos extraoculares, uno o ambos ojos'),
('15.5X','Transposición de músculos extraoculares'),
('15.6X','Revisión de intervención quirúrgica sobre músculo extraocular'),
('20.01','Miringotomía con inserción de tubo'),
('20.09','Otra miringotomía'),
('20.41','Mastoidectomía simple'),
('20.42','Mastoidectomía radical'),
('20.49','Otra mastoidectomía'),
('23.01','Extracción de diente caduco'),
('23.09','Extracción de otro diente'),
('23.11','Extracción de raíz residual'),
('23.19','Otra extracción quirúrgica de diente'),
('23.2X','Restauración de diente mediante obturaciones'),
('23.71','Tratamiento de conducto radicular con irrigación'),
('24.31','Excisión de lesión o de tejido de encía'),
('24.4X','Excisión de lesión maxilar de origen dentario'),
('27.49','Otra excisión de boca'),
('27.54','Reparación de labio fisurado'),
('27.59','Otra reparación plástica de la boca'),
('27.62','Corrección de paladar fisurado (estafilorrafia) (L)'),
('27.63','Revisión de reparación de paladar fisurado'),
('28.0X','Incisión y drenaje de amígdala y estructuras periamigdalinas'),
('28.2X','Amigdalectomía sin adenoidectomía'),
('28.3X','Amigdalectomía con adenoidectomía'),
('28.4X','Extirpación de resto amigdalino'),
('28.6X','Adenoidectomía sin amigdalectomía'),
('28.7X','Control de hemorragia después de amigdalectomía y adenoidectomía'),
('28.91','Extracción de cuerpo extraño de la amígdala y adenoides por incisión'),
('28.92','Excisión de lesión de amígdala y adenoides'),
('28.99','Otras operaciones sobre amígdala y adenoides'),
('29.33','Faringectomía (parcial)'),
('29.39','Otra excisión o resección de lesión o tejido de la faringe'),
('29.91','Dilatación de faringe'),
('29.92','Sección del nervio glosofaríngeo'),
('29.99','Otras operaciones sobre faringe'),
('30.01','Marsupialización de quiste laríngeo'),
('30.09','Otra excisión o destrucción de lesión o tejido de la laringe'),
('34.01','Incisión de pared torácica'),
('34.02','Toracotomía exploratoria'),
('34.03','Reapertura a través de toracotomía reciente'),
('34.04','Inserción de catéter intercostal para drenaje'),
('34.05','Creación de derivación pleuroperitoneal'),
('34.09','Otra incisión de pleura'),
('34.0A','Sello de agua'),
('37.78','Inserción de un sistema de marcapasos transvenoso temporal'),
('37.80','Inserción de marcapasos permanente, inicial o sustituido, sin especificar tipo de aparato'),
('37.81','Inserción inicial de un dispositivo de cámara única, no especificado como respuesta en frecuencia'),
('37.82','Inserción inicial de un aparato de cámara única, con respuesta en frecuencia'),
('37.83','Inserción inicial de dispositivo de doble cámara'),
('37.85','Sustitución de cualquier tipo de marcapasos con aparato de cámara única, no especificado como con respuesta en frecuencia'),
('37.86','Sustitución de cualquier tipo de marcapasos con aparato de cámara única, con respuesta en frecuencia'),
('37.87','Sustitución de cualquier tipo de marcapasos con dispositivo de cámara doble'),
('37.89','Revisión o extracción de marcapasos cardiaco'),
('38.59','Ligadura y extirpación de venas varicosas, venas de miembros inferiores'),
('38.91','Cateterismo arterial'),
('38.92','Cateterismo de vena umbilical'),
('38.93','Cateterismo venoso, no clasificado bajo otro concepto'),
('38.95','Cateterismo venoso para diálisis renal'),
('40.41','Disección radical de cuello, unilateral'),
('40.42','Disección radical de cuello, bilateral'),
('41.43','Esplenectomía parcial'),
('41.5X','Esplenectomía total'),
('44.21','Dilatación de píloro mediante incisión'),
('44.22','Dilatación endoscópica de píloro'),
('44.29','Otra piloroplastía'),
('44.40','Sutura de úlcera péptica no especificada de otra manera'),
('44.41','Sutura de úlcera gástrica'),
('44.42','Sutura de úlcera duodenal'),
('44.43','Control endoscópico de hemorragia gástrica o duodenal'),
('44.44','Embolización por catéter de una hemorragia gástrica o duodenal'),
('44.49','Otro control de hemorragia de estómago o duodeno'),
('44.66','Otros procedimientos para la creación de competencia esfinteriana esofagogástrica'),
('44.91','Ligadura de várices gástricas'),
('45.50','Aislamiento de segmento intestinal, no especificado de otra manera'),
('45.51','Aislamiento de segmento de intestino delgado'),
('45.52','Aislamiento de segmento de intestino grueso'),
('45.61','Resección segmentaria múltiple de intestino delgado'),
('45.62','Otra resección parcial de intestino delgado'),
('45.63','Resección total de intestino delgado'),
('45.71','Resección segmentaria múltiple abierta y otra resección segmentaria múltiple de intestino grueso'),
('45.72','Cecectomía abierta y otra cecectomía'),
('45.73','Hemicolectomía derecha abierta y otra hemicolectomía derecha'),
('45.74','Resección abierta de colon transverso y otra resección de colon transverso'),
('45.75','Hemicolectomía izquierda abierta y otra hemicolectomía izquierda'),
('45.76','Sigmoidectomía abierta y otra sigmoidectomía'),
('45.79','Otra excisión parcial y la no especificada de intestino grueso'),
('45.7A','Resección segmental múltiple de intestino grueso por laparoscopía'),
('45.7B','Ciegotomía laparoscópica'),
('45.7C','Hemicolectomía derecha por laparoscopía'),
('45.7D','Resección de colon transverso por laparoscopía'),
('45.7E','Hemicolectomía izquierda por laparoscopía'),
('45.7F','Sigmoidectomía por laparoscopía'),
('45.7G','Otra excisión parcial de intestino grueso por laparoscopía'),
('45.81','Colectomía intraabdominal total laparoscópica'),
('45.82','Colectomía intraabdominal total abierta'),
('45.83','Otra colectomía intraabdominal total y la no especificada'),
('45.90','Anastomosis intestinal, no especificada de otra manera'),
('45.91','Anastomosis de intestino delgado a intestino delgado'),
('45.92','Anastomosis de intestino delgado al muñón rectal'),
('45.93','Otra anastomosis de intestino delgado a intestino grueso'),
('45.94','Anastomosis de intestino grueso a intestino grueso'),
('45.95','Anastomosis al ano'),
('46.10','Colostomía, no especificada de otra manera'),
('46.11','Colostomía temporal'),
('46.13','Colostomía permanente'),
('46.14','Apertura retardada de colostomía'),
('46.20','lleostomía, no especificada de otra manera'),
('46.21','lleostomía temporal'),
('46.22','lleostomía continente'),
('46.23','Otra ileostomía permanente'),
('46.24','Apertura retardada de ileostomía'),
('46.80','Manipulación intraabdominal de intestino, no especificada de otra manera'),
('46.81','Manipulación intraabdominal de intestino delgado'),
('46.82','Manipulación intraabdominal de intestino grueso'),
('46.85','Dilatación del intestino'),
('47.01','Apendicectomía laparoscópica'),
('47.09','Otra apendicectomía'),
('47.11','Apendicectomía incidental laparoscópica'),
('47.19','Otra apendicectomía incidental'),
('48.73','Cierre de otra fístula rectal'),
('48.93','Reparación de fístula perirrectal'),
('49.01','Incisión de absceso perianal'),
('49.02','Otra incisión de tejido perianal'),
('49.11','Fistulotomía anal'),
('49.12','Fistulectomía anal'),
('49.39','Otra extirpación local o eliminación (destrucción) de lesión o de tejido de ano'),
('49.41','Reducción de hemorroides'),
('49.42','Inyección (esclerosis) de hemorroides'),
('49.43','Cauterización de hemorroides'),
('49.44','Destrucción de hemorroides por crioterapia'),
('49.45','Ligamento de hemorroides'),
('49.46','Extirpación de hemorroides'),
('49.47','Evacuación de hemorroides trombosadas'),
('49.49','Otros procedimientos sobre hemorroides'),
('49.51','Esfinterotomía anal lateral izquierda'),
('49.52','Esfinterotomía anal posterior'),
('49.59','Otra esfinterotomía anal'),
('49.73','Cierre de fístula anal'),
('51.22','Colecistectomía'),
('51.23','Colecistectomía laparoscópica'),
('51.41','Exploración del conducto biliar principal para extracción de cálculo'),
('51.42','Exploración del conducto biliar principal para alivio de otra obstrucción'),
('51.43','Inserción de tubo coledocohepático para descompresión'),
('51.49','Incisión de otros conductos biliares para alivio de obstrucción'),
('51.51','Exploración de colédoco'),
('51.59','Incisión de otro conducto biliar'),
('53.00','Reparación unilateral de hernia inguinal, no especificada de otra manera'),
('53.01','Reparación abierta y otra reparación de hernia inguinal directa'),
('53.02','Reparación abierta y otra reparación de hernia inguinal indirecta'),
('53.03','Reparación abierta y otra reparación de hernia inguinal directa con injerto o prótesis'),
('53.04','Reparación abierta y otra reparación de hernia inguinal indirecta con injerto o prótesis'),
('53.05','Reparación de hernia inguinal con injerto o prótesis no especificada de otra manera'),
('53.10','Reparación bilateral de hernia inguinal, no especificada de otra manera'),
('53.11','Reparación abierta y otra reparación bilateral de hernia inguinal directa'),
('53.12','Reparación abierta y otra reparación bilateral de hernia inguinal indirecta'),
('53.13','Reparación abierta y otra reparación bilateral de hernia inguinal, una directa y otra indirecta'),
('53.14','Reparación abierta y otra reparación bilateral de hernia inguinal directa con injerto o prótesis'),
('53.15','Reparación abierta y otra reparación bilateral de hernia inguinal indirecta con injerto o prótesis'),
('53.16','Reparación abierta y otra reparación bilateral de hernia inguinal, una directa y una indirecta, con injerto o prótesis'),
('53.17','Reparación bilateral de hernia inguinal con injerto o prótesis, no especificada de otra manera'),
('53.21','Reparación unilateral de hernia crural con injerto o prótesis'),
('53.29','Otra herniorrafia de hernia crural unilateral'),
('53.31','Reparación bilateral de hernia crural con injerto o prótesis'),
('53.39','Otra herniorrafia crural bilateral'),
('53.41','Reparación abierta y otra reparación de hernia umbilical con injerto o prótesis'),
('53.42','Reparación laparoscópica de hernia umbilical con injerto o prótesis'),
('53.43','Otra reparación laparoscópica de hernia umbilical'),
('53.49','Otra herniorrafia umbilical abierta'),
('53.51','Reparación de hernia incisional (eventración)'),
('53.59','Reparación de otra hernia de la pared abdominal anterior'),
('53.61','Otra reparación abierta de hernia incisional (eventración) con injerto o prótesis'),
('53.69','Reparación abierta y otra reparación de otra hernia de la pared abdominal anterior con injerto o prótesis'),
('53.71','Reparación laparoscópica de hernia diafragmática, abordaje abdominal'),
('53.72','Reparación abierta y otra reparación de hernia diafragmática, abordaje abdominal'),
('53.75','Reparación de hernia diafragmática, abordaje abdominal, no especificada de otra manera'),
('53.80','Reparación de hernia diafragmática con acceso torácico, no especificada de otra manera'),
('53.81','Plicatura de diafragma'),
('53.82','Reparación de hernia parasternal (Morgagni)'),
('53.83','Reparación laparoscópica de hernia diafragmática, con abordaje torácico'),
('53.84','Reparación abierta y otra reparación de hernia diafragmática, abordaje torácico'),
('54.11','Laparotomía exploradora'),
('54.21','Laparoscopia'),
('54.25','Lavado peritoneal'),
('54.51','Lisis laparoscópica de adherencias peritoneales'),
('54.59','Otras lisis de adherencias peritoneales'),
('56.2X','Ureterotomía'),
('57.94','Inserción de catéter urinario permanente'),
('58.6X','Dilatación de uretra'),
('59.8X','Cateterismo ureteral'),
('60.29','Otra prostatectomía transuretral'),
('60.61','Excisión local de lesión de próstata'),
('60.69','Otra prostatectomía'),
('62.5X','Orquiopexia'),
('63.52','Reducción de torsión de testículo o cordón espermático'),
('63.73','Vasectomía sin bisturí'),
('64.0X','Circuncisión'),
('64.2X','Excisión local o destrucción de lesión de pene'),
('65.01','Ooforotomía laparoscópica'),
('65.09','Otra ooforotomía'),
('65.21','Marsupialización de quiste ovárico'),
('65.22','Resección en cuña de ovario'),
('65.23','Marsupialización laparoscópica de quiste ovárico'),
('65.24','Resección en cuña laparoscópica de ovario'),
('65.25','Otra excisión local o destrucción laparoscópica de ovario'),
('65.31','Ooforectomía unilateral laparoscópica'),
('65.39','Otra ooforectomía unilateral'),
('65.41','Salpingooforectomía unilateral laparoscópica'),
('65.49','Otra salpingooforectomía unilateral'),
('65.51','Otra extirpación de ambos ovarios en un mismo acto operatorio'),
('65.52','Otra extirpación de ovario restante'),
('65.53','Extirpación laparoscópica de ambos ovarios en un mismo acto operatorio'),
('65.54','Extirpación laparoscópica de ovario restante'),
('65.61','Otra extirpación de ambos ovarios y trompas en un mismo acto operatorio'),
('65.62','Otra extirpación de ovario y trompa restantes'),
('65.63','Extirpación laparoscópica de ambos ovarios y trompas en un mismo acto operatorio'),
('65.64','Extirpación laparoscópica de ovario y trompa restantes'),
('65.95','Liberación de torsión de ovario'),
('66.01','Salpingotomía'),
('66.02','Salpingostomía'),
('66.31','Otra ligadura y aplastamiento bilateral de las trompas de Falopio'),
('66.32','Otra ligadura y sección bilateral de las trompas de Falopio'),
('66.39','Otra destrucción u oclusión bilateral de las trompas de Falopio'),
('67.11','Biopsia endocervical'),
('67.12','Otra biopsia cervical'),
('67.19','Otros procedimientos diagnósticos sobre el cuello uterino'),
('67.2X','Conización'),
('67.32','Destrucción de lesión del cuello uterino por cauterización'),
('67.33','Destrucción de lesión del cuello uterino por criocirugía'),
('67.39','Otra excisión o destrucción de lesión o tejido del cuello uterino'),
('68.16','Biopsia cerrada de útero'),
('68.23','Ablación endometrial'),
('68.29','Otra excisión o destrucción de lesión del útero'),
('68.31','Histerectomía supracervical laparoscópica [HSL]'),
('68.39','Otra histerectomía subtotal abdominal y la no especificada'),
('68.41','Histerectomía total abdominal laparoscópica'),
('68.49','Otra histerectomía total abdominal y la no especificada'),
('68.51','Histerectomía vaginal asistida por laparoscopia (HVAL)'),
('68.59','Otra histerectomía vaginal y la no especificada'),
('69.01','Dilatación y legrado para terminación del embarazo'),
('69.02','Dilatación y legrado después de parto o aborto'),
('69.09','Otra dilatación y legrado'),
('69.41','Sutura de desgarro de útero'),
('69.52','Legrado por aspiración del útero después de parto o aborto'),
('69.59','Otro legrado por aspiración del útero'),
('69.7X','Inserción de dispositivo anticonceptivo intrauterino'),
('70.33','Excisión o destrucción de lesión de vagina'),
('70.50','Reparación de cistocele y rectocele'),
('70.51','Reparación de cistocele'),
('70.52','Reparación de rectocele'),
('70.79','Otra reparación de vagina'),
('71.9X','Otras operaciones sobre los órganos genitales femeninos'),
('74.0X','Cesárea clásica'),
('74.1X','Cesárea clásica baja'),
('75.50','Reparación de desgarro obstétrico actual del útero, no especificado de otra manera'),
('75.51','Reparación de desgarro obstétrico actual del cuello uterino'),
('75.52','Reparación de desgarro obstétrico actual del cuerpo uterino'),
('77.00','Secuestrectomía, sitio no especificado'),
('77.01','Secuestrectomía, escápula, clavícula y tórax [costillas y esternón]'),
('77.02','Secuestrectomía, húmero'),
('77.03','Secuestrectomía, rádio y cúbito'),
('77.04','Secuestrectomía, carpianos y metacarpianos'),
('77.05','Secuestrectomía, fémur'),
('77.06','Secuestrectomía, rótula'),
('77.07','Secuestrectomía, tibia y peroné'),
('77.08','Secuestrectomía, tarsianos y metatarsianos'),
('77.09','Secuestrectomía, otro (falanges (de pie) (de mano), huesos pelvianos, vértebras)'),
('77.25','Osteotomía en cuña, fémur'),
('78.17','Aplicación de dispositivo fijador externo, tibia y peroné'),
('78.57','Fijación interna del hueso sin reducción de fractura, tibia y peroné'),
('78.67','Extracción de dispostivios implantados en el hueso, tibia y peroné'),
('79.01','Reduccióncerrada de fractura sin fijación interna, húmero'),
('79.02','Reducción cerrada de fractura sin fijación, rádio y cúbito'),
('79.03','Reducción cerrada de fractura sin fijación, carpianos y metacarpianos'),
('79.04','Reducción cerrada de fractura sin fijación, falanges y mano'),
('79.05','Reducción cerrada de fractura sin fijación, fémur'),
('79.06','Reducción cerrada de fractura sin fijación, tibia y peroné'),
('79.07','Reducción cerrada de fractura sin fijación, tarsianos y metatarsianos'),
('79.08','Reducción cerrada de fractura sin fijación, falanges y pie'),
('79.11','Reducción cerrada de fractura con fijación interna, húmero'),
('79.12','Reducción cerrada de fractura con fijación interna, radio y cúbito'),
('79.13','Reducción cerrada de fractura con fijación interna, carpianos y metacarpianos'),
('79.14','Reducción cerrada de fractura con fijación interna, falanges y mano'),
('79.15','Reducción cerrada de fractura con fijación interna, fémur'),
('79.16','Reducción cerrada de fractura con fijación interna, tibia y peroné'),
('79.17','Reducción cerrada de fractura con fijación interna, tarsianos y metatarsianos'),
('79.18','Reducción cerrada de fractura con fijación interna, falanges y pie'),
('79.19','Reducción cerrada de fractura con fijación interna, otros huesos específicos'),
('79.21','Reducción abierta de fractura sin fijación interna, húmero'),
('79.22','Reducción abierta de fractura sin fijación, radio y cúbito'),
('79.23','Reducción abierta de fractura sin fijación, carpianos y metacarpianos'),
('79.24','Reducción abierta de fractura sin fijación, falanges y mano'),
('79.25','Reducción abierta de fractura sin fijación, fémur'),
('79.26','Reducción abierta de fractura sin fijación, tibia y peroné'),
('79.27','Reducción abierta de fractura sin fijación, tarsianos y metatarsianos'),
('79.28','Reducción abierta de fractura sin fijación, falanges y pie'),
('79.29','Reducción abierta de fractura sin fijación, otros huesos específicos'),
('79.31','Reducción abierta de fractura con fijación interna, húmero'),
('79.32','Reducción abierta de fractura con fijación, radio y cúbito'),
('79.33','Reducción abierta de fractura con fijación, carpianos y metacarpianos'),
('79.34','Reducción abierta de fractura con fijación, falanges y mano'),
('79.35','Reducción abierta de fractura con fijación, fémur'),
('79.36','Reducción abierta de fractura con fijación, tibia y peroné'),
('79.37','Reducción abierta de fractura con fijación, tarsianos y metatarsianos'),
('79.38','Reducción abierta de fractura con fijación, falanges y pie'),
('79.39','Reducción abierta de fractura con fijación, otros huesos específicos'),
('79.41','Reducción cerrada de epífisis separada, húmero'),
('79.42','Reducción cerrada de epífisis separada, radio y cúbito'),
('79.43','Reducción cerrada de epífisis separada, carpianos y metacarpianos'),
('79.44','Reducción cerrada de epífisis separada, falanges y mano'),
('79.45','Reducción cerrada de epífisis separada, fémur'),
('79.46','Reducción cerrada de epífisis separada, tibia y Perone'),
('79.49','Reducción cerrada de epífisis separada, otros huesos específicos'),
('79.51','Reducción abierta de epífisis separada, húmero'),
('79.52','Reducción abierta de epífisis separada, radio y cúbito'),
('79.53','Reducción abierta de epífisis separada, carpianos y metacarpianos'),
('79.54','Reducción abierta de epífisis separada, falanges y mano'),
('79.55','Reducción abierta de epífisis separada, fémur'),
('79.56','Reducción abierta de epífisis separada, tibia y peroné'),
('79.59','Reducción abierta de epífisis separada, otros huesos específicos'),
('79.61','Debridamiento de sitio de fractura abierta. Sitio no especificado'),
('79.62','Debridamiento de sitio de fractura abierta, radio y cúbito'),
('79.63','Debridamiento de sitio de fractura abierta, carpianos y metacarpianos'),
('79.64','Debridamiento de sitio de fractura abierta, falanges y mano'),
('79.65','Debridamiento de sitio de fractura abierta, fémur'),
('79.66','Debridamiento de sitio de fractura abierta, tibia y peroné'),
('79.69','Debridamiento de sitio de fractura abierta, otros huesos específicos'),
('79.70','Reducción cerrada de luxación de sitio no especificado'),
('79.71','Reducción cerrada de luxación de hombro'),
('79.72','Reducción cerrada de luxación de codo'),
('79.73','Reducción cerrada de luxación de muñeca'),
('79.74','Reducción cerrada de luxación de mano y dedo de mano'),
('79.75','Reducción cerrada de luxación de cadera'),
('79.76','Reducción cerrada de luxación de rodilla'),
('79.77','Reducción cerrada de luxación de tobillo'),
('79.78','Reducción cerrada de luxación de pie y dedo de pie'),
('79.79','Reducción cerrada de luxación de otros sitios especificados'),
('79.80','Reducción abierta de luxación de sitio no especificado'),
('79.81','Reducción abierta de luxación de hombro'),
('79.82','Reducción abierta de luxación de codo'),
('79.83','Reducción abierta de luxación de muñeca'),
('79.84','Reducción abierta de luxación de mano y dedo de mano'),
('79.85','Reducción abierta de luxación de cadera'),
('79.86','Reducción abierta de luxación de rodilla'),
('79.87','Reducción abierta de luxación de tobillo'),
('79.88','Reducción abierta de luxación de pie y dedo de pie'),
('79.89','Reducción abierta de luxación de otros sitios especificados'),
('80.16','Otra artotomía, rodilla'),
('80.26','Artroscopía, rodilla'),
('80.70','Sinovectomía, sitio no especificado'),
('80.71','Sinovectomía, hombro'),
('80.72','Sinovectomía, codo'),
('80.73','Sinovectomía, muñeca'),
('80.74','Sinovectomía, mano y dedos de la mano'),
('80.75','Sinovectomía, cadera'),
('80.76','Sinovectomía, rodilla'),
('80.77','Sinovectomía, tobillo'),
('80.78','Sinovectomía, pie y dedos del pie'),
('80.79','Sinocextomía, otros sitios no especificados (columna vertebral)'),
('81.40','Reparación de cadera, no especificada bajo otro concepto'),
('81.42','Reparación “cinco en uno” de rodilla'),
('81.43','Reparación de una triada de rodilla'),
('81.44','Estabilización de rótula'),
('81.45','Otra reparación de los ligamentos cruzados'),
('81.46','Otra reparación de los ligamentos colaterales'),
('81.47','Otra reparación de rodilla'),
('81.52','Sustitución parcial de cadera'),
('81.54','Sustitución total de rodilla'),
('81.55','Revisión de sustitución de rodilla, no especificada en otra parte'),
('83.11','Tenotomía de Aquiles'),
('83.12','Tenotomía de aductor de cadera'),
('83.39','Excisión de lesión de otro tejido blando'),
('84.00','Amputación de miembro superior, no especificada de otra manera'),
('84.01','Amputación y desarticulación de dedo de mano'),
('84.02','Amputación y desarticulación de dedo pulgar'),
('84.03','Amputación a través de mano'),
('84.04','Desarticulación de muñeca'),
('84.05','Amputación a través de antebrazo'),
('84.06','Desarticulación de codo'),
('84.07','Amputación a través de húmero'),
('84.08','Desarticulación de hombro'),
('84.09','Amputación intertoracoescapular'),
('84.10','Amputación de miembro inferior, no especificada de otra manera'),
('84.11','Amputación de dedo de pie'),
('84.12','Amputación a través de pie'),
('84.13','Desarticulación de tobillo'),
('84.14','Amputación de tobillo a través de maléolos de tibia y peroné'),
('84.15','Otra amputación debajo de la rodilla'),
('84.16','Desarticulación de rodilla'),
('84.17','Amputación por encima de la rodilla'),
('84.18','Desarticulación de cadera'),
('84.19','Amputación abdominopélvica'),
('86.11','Biopsia de piel y tejido subcutáneo'),
('86.21','Extirpación de quiste o seno pilonidal'),
('86.22','Desbridamiento excisional de herida, infección o quemadura'),
('86.23','Extracción de uña, lecho de uña o pliegue de uña'),
('86.24','Quimiocirugía de piel'),
('86.25','Abrasión dérmica'),
('86.26','Ligadura de apéndice dérmico'),
('86.27','Desbridamiento de uña, base de uña o pliegue de uña'),
('86.28','Desbridamiento no excisional de herida, infección o quemadura'),
('86.3X','Otra extirpación local o destrucción de lesión o tejido de piel y tejido subcutáneo'),
('86.4X','Extirpación radical de lesión cutánea'),
('86.51','Reimplantación de cuero cabelludo'),
('86.59','Cierre de piel y tejido subcutáneo de otros sitios'),
('86.91','Excisión de piel para injerto'),
('86.92','Electrolisis y otra depilación de piel'),
('86.93','Inserción de expansor de tejidos'),
('86.94','Inserción o sustitución de neuroestimulador generador de pulsos de un solo electrodo, no especificado como recargable'),
('86.95','Inserción o sustitución de neuroestimulador generador de pulsos de disposición dual'),
('86.96','Inserción o sustitución de otro neuroestimulador generador de pulsos'),
('86.97','Inserción o sustitución de neuroestimulador generador de pulsos recargable de electrodo único'),
('86.98','Inserción o sustitución de neuroestimulador generador de pulsos recargable de doble electrodo'),
('86.99','Otras operaciones sobre piel y tejido subcutáneo'),
('89.02','Entrevista y evaluación, descritas como limitadas'),
('89.03','Entrevista y evaluación, descritas como globales'),
('89.26','Examen ginecológico'),
('89.31','Examen dental'),
('89.36','Examen manual de mama'),
('89.7X','Reconocimiento médico general'),
('93.11','Ejercicio asistido'),
('93.12','Otro ejercicio activo musculoesquelético'),
('93.13','Ejercicios resistidos'),
('93.14','Entrenamiento en movimientos de articulaciones'),
('93.15','Movilización de columna'),
('93.16','Movilización de otras articulaciónes'),
('93.17','Otro ejercicio pasivo musculoesquelético'),
('93.18','Ejercicio respiratorio'),
('93.19','Ejercicio, no clasificado bajo otro concepto'),
('93.21','Tracción manual y mecánica'),
('93.22','Marcha y entrenamiento de la marcha'),
('93.23','Adaptación de dispositivo ortésico'),
('93.24','Entrenamiento en el uso de dispositivo ortésico y protésico'),
('93.25','Extensión forzada de miembro'),
('93.26','Liberación manual de adherencias articulares'),
('93.27','Estiramiento de músculo o tendón'),
('93.28','Estiramiento de fascia'),
('93.29','Otra corrección forzada de extremidad'),
('93.31','Ejercicio asistido en piscina'),
('93.32','Tratamiento en baño de remolino'),
('93.33','Otra hidroterapia'),
('93.34','Diatermia'),
('93.35','Otra terapia térmica'),
('93.36','Reentrenamiento cardiaco'),
('93.37','Entrenamiento prenatal'),
('93.38','Fisioterapia combinada sin mención de los componentes'),
('93.39','Otra fisioterapia'),
('93.51','Aplicación de vendaje enyesado'),
('93.52','Aplicación de soporte cervical'),
('93.54','Aplicación de férula'),
('93.56','Aplicación de vendaje de presión'),
('93.59','Otra inmovilización, presión y cuidado de herida'),
('94.35','Intervención en crisis'),
('94.38','Psicoterapia verbal de apoyo'),
('95.09','Examen oftalmológico, no especificado de otra manera'),
('95.42','Prueba clínica de audición'),
('95.47','Examen de la audición no especificado de otra manera'),
('96.54','Eliminación de sarro, pulido y desbridamiento de dientes'),
('97.15','Sustitución de catéter de herida'),
('97.41','Extracción de tubo de toracotomía o de drenaje de la cavidad pleural'),
('97.62','Extracción de tubo de ureterostomía y de catéter ureteral'),
('97.63','Extracción de tubo de cistostomía'),
('97.64','Extracción de otro dispositivo de drenaje urinario'),
('97.88','Extracción de dispositivo de inmovilización externo'),
('98.51','Litotricia por ondas de choque extracorporales del riñón, del uréter y de la vejiga'),
('99.16','Inyección de antídoto'),
('99.33','Vacunación contra tuberculosis'),
('99.39','Administración de vacuna combinada de difteria.tétanos-tosferina'),
('99.3A','Administración de vacuna pentavalente (DPT, HB, Hib)'),
('99.3B','Vacunación contra difteria y tétanos (Td)'),
('99.3C','Vacunación contra neumococo 23 valente'),
('99.3D','Vacunación contra neumococo conjugado (heptavalente)'),
('99.41','Administración de vacuna contra la poliomielitis (Sabin)'),
('99.44','Vacunación contra rabia'),
('99.48','Administración de vacuna contra el sarampión, -parotiditis-rubéola'),
('99.4A','Vacunación contra rotavirus'),
('99.4C','Vacunación contra hepatitis B (HB)'),
('99.4F','Vacunación contra sarampión y rubéola (SR) (doble viral)'),
('99.4G','Vacunación contra el virus del papiloma humano'),
('99.52','Vacunación profiláctica contra la gripe [influenza]');